# Generated by agent-repo. Hooks and CI call only these verbs. Operator only.
SHELL := /bin/bash
GATE := python3 -I -B gates/gate.py
unexport VIRTUAL_ENV
COMPONENTS := backend-py 
.DEFAULT_GOAL := help
.PHONY: help setup setup-gates doctor fix lint typecheck test-core check check-repo test contract contract-check \
	client client-check db-check db-schema decisions adr-find adr-new migration-new sync gates-selftest gates-bench \
	controls-baseline controls-anchor suppress-baseline up down

-include mk/*.mk

help: ## List every verb
	@grep -hE '^[a-z0-9][a-z0-9 -]*:.*## ' $(MAKEFILE_LIST) | sed -E 's/:[^#]*## /\t/' | sort

setup: setup-gates $(addprefix setup-,$(COMPONENTS)) ## Install every toolchain from its lockfile
	@$(GATE) mark-setup
	@echo "RESULT: PASS setup"

setup-gates: ## Check the tools the gates need (never installs silently)
	@command -v python3 >/dev/null || { echo "python3 missing"; exit 1; }
	@command -v ast-grep >/dev/null || { echo "ast-grep missing: see README.md, section Prerequisites"; exit 1; }

doctor: ## Check hooks, manifest, tools and AGENTS.md
	@$(GATE) doctor

fix: $(addprefix fix-,$(COMPONENTS)) ## Apply every formatter

lint: $(addprefix lint-,$(COMPONENTS)) check-repo ## Format check, linters, boundaries, house rules, drift

typecheck: $(addprefix typecheck-,$(COMPONENTS)) ## Strict type checks

test-core: $(addprefix test-core-,$(COMPONENTS)) ## Offline core and adapter tests

check: ## What the stop gate runs, for the touched components only
	@cs=$$($(GATE) touched) || { echo "RESULT: FAIL check (gate.py touched failed)"; exit 1; }; \
	for c in $$cs; do $(MAKE) -s check-$$c || exit 1; done; echo "RESULT: PASS check"

check-repo: ## Repo rules, drift checks and the sync check
	@$(GATE) check-repo >/dev/null || $(GATE) check-repo
	@$(GATE) drift >/dev/null || $(GATE) drift

test: up $(addprefix test-,$(COMPONENTS)) ## Stack up, behaviour and contract tests, stack down
	@$(MAKE) -s down

decisions: ## Regenerate decisions/index.md
	@$(GATE) adr index

adr-find: ## Find decisions: make adr-find TAG=<tag> Q=<text>
	@$(GATE) adr find --tag "$(TAG)" --query "$(Q)"

adr-new: ## Create the next ADR (ask the operator first): make adr-new TITLE="..."
	@$(GATE) adr new --title "$(TITLE)"

sync: ## Operator: regenerate settings.json, rules, CODEOWNERS and rule notes from gates/
	@$(GATE) sync

gates-selftest: ## Prove that every gate turns red on its fixture
	@$(GATE) selftest

gates-bench: ## Time the in-turn checks
	@$(GATE) bench

controls-baseline: ## Operator: write gates/controls.sha256 after changing a control file
	@$(GATE) baseline

controls-anchor: ## Operator, without a remote: point refs/gates/baseline at the committed baseline
	@$(GATE) anchor

suppress-baseline: ## Operator: accept the current inline suppressions: make suppress-baseline REASON=<issue-url>
	@$(GATE) suppress-baseline --reason "$(REASON)"

contract contract-check client client-check: ## API contract verbs (need opt/contract)
	@echo "$@: not configured"
migration-new: ## New migration (needs postgres)
	@echo "migration-new: not configured"
