"""ADR mechanics: format, chain, references, generated index, find and new."""

from __future__ import annotations

import fcntl
import json
import os
import re
import time
from typing import Dict, List, Optional, Set

from . import gitx
from .findings import Finding

NAME = re.compile(r"^(\d{4})-[a-z0-9-]+\.md$")
MENTION = re.compile(r"\bADR-(\d{4})\b")
STATUSES = ("proposed", "accepted", "superseded", "deprecated")
MAX_LINES = 50
HEADINGS = {"de": ("Kontext", "Entscheidung", "Konsequenz"), "en": ("Context", "Decision", "Consequence")}
TEXT_SUFFIXES = (".md", ".json", ".py", ".yml", ".yaml", ".sh", ".ts", ".kt", ".kts", ".sql", ".html", ".css",
                 ".toml", ".go", ".rs", ".txt", ".mk")
TEXT_NAMES = ("Makefile",)


def frontmatter(text: str) -> Dict[str, str]:
    """Parse the flat key: value frontmatter between the first two '---' lines."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}
    out = {}
    for line in lines[1:]:
        if line.strip() == "---":
            return out
        key, _, value = line.partition(":")
        out[key.strip()] = value.strip()
    return {}


def record_list(tree: str) -> List[dict]:
    """Return every ADR file with its number, path, frontmatter and line count; duplicates stay visible."""
    out = []
    for rel in gitx.ls(tree, ["decisions/*.md"]):
        match = NAME.match(os.path.basename(rel))
        if not match:
            continue
        with open(os.path.join(tree, rel), encoding="utf-8") as handle:
            text = handle.read()
        out.append({"number": int(match.group(1)), "path": rel, "meta": frontmatter(text),
                    "lines": len(text.splitlines())})
    return out


def records(tree: str) -> Dict[int, dict]:
    """Return ADRs by number; with duplicates the first path wins here and violations() reports the rest."""
    out: Dict[int, dict] = {}
    for rec in record_list(tree):
        out.setdefault(rec["number"], rec)
    return out


def taken_numbers(tree: str) -> Set[int]:
    """Return ADR numbers used in any worktree of this repository or on any local or remote branch."""
    numbers = {rec["number"] for rec in record_list(tree)}
    listing = gitx.run(["git", "worktree", "list", "--porcelain"], cwd=tree).stdout
    for line in listing.splitlines():
        path = line[len("worktree "):] if line.startswith("worktree ") else ""
        folder = os.path.join(path, "decisions")
        if path and os.path.isdir(folder):
            numbers |= {int(m.group(1)) for m in (NAME.match(n) for n in os.listdir(folder)) if m}
    refs = gitx.run(["git", "for-each-ref", "--format=%(refname)", "refs/heads", "refs/remotes"], cwd=tree).stdout
    for ref in refs.split():
        names = gitx.run(["git", "ls-tree", "--name-only", ref, "decisions/"], cwd=tree).stdout.split()
        numbers |= {int(m.group(1)) for m in (NAME.match(os.path.basename(n)) for n in names) if m}
    return numbers


def index_text(tree: str) -> str:
    """Render decisions/index.md (for humans; agents use make adr-find)."""
    rows = ["# Decisions", "", "Generated by `make decisions`. Do not edit.", "",
            "| ADR | Title | Status | Tags |", "| --- | --- | --- | --- |"]
    for number, rec in sorted(records(tree).items()):
        meta = rec["meta"]
        rows.append(f"| [{number:04d}]({os.path.basename(rec['path'])}) | {meta.get('title', '')} | "
                    f"{meta.get('status', '')} | {meta.get('tags', '').strip('[]')} |")
    return "\n".join(rows) + "\n"


def violations(tree: str, rule: str) -> List[Finding]:
    """Return format, chain, reference and index findings."""
    recs = records(tree)
    found: List[Finding] = []
    for rel in gitx.ls(tree, ["decisions/*.md"]):
        if os.path.basename(rel) != "index.md" and not NAME.match(os.path.basename(rel)):
            found.append(Finding(rel, 1, rule, "ADR file name must be NNNN-slug.md"))
    for rec in record_list(tree):
        if recs[rec["number"]]["path"] != rec["path"]:
            found.append(Finding(rec["path"], 1, rule, f"duplicate ADR number {rec['number']:04d} "
                                 f"(also {recs[rec['number']]['path']}); renumber with make adr-new"))
    for number, rec in recs.items():
        meta, rel = rec["meta"], rec["path"]
        if meta.get("id", "").lstrip("0") != str(number):
            found.append(Finding(rel, 1, rule, f"frontmatter id must be {number}"))
        if meta.get("status") not in STATUSES:
            found.append(Finding(rel, 1, rule, f"status must be one of {', '.join(STATUSES)}"))
        if not meta.get("tags", "").startswith("["):
            found.append(Finding(rel, 1, rule, "tags must be a [list]"))
        if rec["lines"] > MAX_LINES:
            found.append(Finding(rel, 1, rule, f"ADR has {rec['lines']} lines (max {MAX_LINES})"))
        sup = meta.get("supersedes", "").strip("[] ")
        for ref in [s for s in re.split(r"[,\s]+", sup) if s]:
            if not ref.isdigit() or int(ref) not in recs:
                found.append(Finding(rel, 1, rule, f"supersedes unknown ADR {ref}"))
            elif recs[int(ref)]["meta"].get("status") != "superseded":
                found.append(Finding(recs[int(ref)]["path"], 1, rule,
                                     f"ADR {int(ref):04d} is superseded by {number:04d}; set status: superseded"))
    for rel in gitx.ls(tree, ["**"]):
        if rel.startswith("gates/fixtures/") or not (rel.endswith(TEXT_SUFFIXES) or os.path.basename(rel) in TEXT_NAMES):
            continue
        with open(os.path.join(tree, rel), encoding="utf-8", errors="replace") as handle:
            text = handle.read()
        for match in MENTION.finditer(text):
            if int(match.group(1)) not in recs:
                found.append(Finding(rel, text.count("\n", 0, match.start()) + 1, rule,
                                     f"ADR-{match.group(1)} does not exist"))
    catalog_path = os.path.join(tree, "gates", "catalog.json")
    if os.path.isfile(catalog_path):
        with open(catalog_path, encoding="utf-8") as handle:
            for entry in json.load(handle):
                if entry.get("adr") and int(entry["adr"]) not in recs:
                    found.append(Finding("gates/catalog.json", 1, rule, f"{entry['id']} cites missing ADR {entry['adr']}"))
    index = os.path.join(tree, "decisions", "index.md")
    if recs and (not os.path.isfile(index) or open(index, encoding="utf-8").read() != index_text(tree)):
        found.append(Finding("decisions/index.md", 1, rule, "index is stale; run `make decisions`"))
    return found


def find(tree: str, tag: str = "", query: str = "", limit: int = 10) -> List[str]:
    """Return up to limit 'path: title [tags]' lines matching a tag and a text query."""
    out = []
    for number, rec in sorted(records(tree).items()):
        meta = rec["meta"]
        with open(os.path.join(tree, rec["path"]), encoding="utf-8") as handle:
            body = handle.read().lower()
        if tag and tag.lower() not in meta.get("tags", "").lower():
            continue
        if query and query.lower() not in body:
            continue
        out.append(f"{rec['path']}: {meta.get('title', '')} {meta.get('tags', '')} ({meta.get('status', '')})")
    return out[:limit]


def new(tree: str, title: str, lang: str) -> str:
    """Create the next ADR under a lock in the shared git directory; the number skips every worktree and branch."""
    lock_path = os.path.join(gitx.common_dir(tree), "gates-adr.lock")
    with open(lock_path, "w") as lock:
        deadline = time.time() + 30
        while True:
            try:
                fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
                break
            except OSError:
                if time.time() > deadline:
                    raise RuntimeError("another adr-new holds the lock")
                time.sleep(0.2)
        number = max(taken_numbers(tree), default=0) + 1
        slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")[:60] or "decision"
        rel = f"decisions/{number:04d}-{slug}.md"
        heads = HEADINGS.get(lang, HEADINGS["en"])
        body = (f"---\nid: {number}\ntitle: {title}\nstatus: proposed\ntags: []\n---\n\n"
                f"# ADR-{number:04d}: {title}\n\n{heads[0]}: \n\n{heads[1]}: \n\n{heads[2]}: \n")
        os.makedirs(os.path.join(tree, "decisions"), exist_ok=True)
        with open(os.path.join(tree, rel), "x", encoding="utf-8") as handle:
            handle.write(body)
        return rel


def project(tree: str) -> Optional[dict]:
    """Return gates/project.json if present."""
    path = os.path.join(tree, "gates", "project.json")
    if not os.path.isfile(path):
        return None
    with open(path, encoding="utf-8") as handle:
        return json.load(handle)
